import { boolean, integer, numeric, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const sources = pgTable("sources", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull(), provider: text("provider").notNull(), name: text("name").notNull(), status: text("status").notNull(), accountName: text("account_name"), accountId: text("account_id"), lastSyncAt: timestamp("last_sync_at", { withTimezone: true }), nextSyncAt: timestamp("next_sync_at", { withTimezone: true }), recordsImported: integer("records_imported").notNull(), lastSyncDurationMs: integer("last_sync_duration_ms"), dataFreshness: text("data_freshness"), createdAt: timestamp("created_at", { withTimezone: true }).notNull() });
export const campaigns = pgTable("campaigns", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull(), externalId: text("external_id"), name: text("name").notNull(), source: text("source").notNull(), status: text("status").notNull(), spend: numeric("spend").notNull(), revenue: numeric("revenue").notNull(), roas: numeric("roas").notNull(), cpa: numeric("cpa").notNull(), impressions: integer("impressions").notNull(), clicks: integer("clicks").notNull(), conversions: integer("conversions").notNull(), currency: text("currency").notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull() });
export const creators = pgTable("creators", { id: text("id").primaryKey(), handle: text("handle").notNull(), platform: text("platform").notNull(), displayName: text("display_name"), bio: text("bio"), followers: integer("followers").notNull().default(0), engagementRate: numeric("engagement_rate").notNull().default("0"), profileUrl: text("profile_url"), rawData: text("raw_data"), enrichedAt: timestamp("enriched_at", { withTimezone: true }) });
export const syncJobs = pgTable("sync_jobs", { id: text("id").primaryKey(), kind: text("kind").notNull(), status: text("status").notNull(), message: text("message"), recordsSynced: integer("records_synced").notNull().default(0), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull() });
export const dailyMetrics = pgTable("daily_metrics", { id: text("id").primaryKey(), metricDate: text("metric_date").notNull(), revenue: numeric("revenue").notNull().default("0"), spend: numeric("spend").notNull().default("0"), orders: integer("orders").notNull().default(0), customers: integer("customers").notNull().default(0), conversions: integer("conversions").notNull().default(0), impressions: integer("impressions").notNull().default(0), clicks: integer("clicks").notNull().default(0) });
export const customers = pgTable("customers", { id: text("id").primaryKey(), email: text("email").notNull(), name: text("name"), totalPurchases: integer("total_purchases").notNull().default(0), totalRevenue: numeric("total_revenue").notNull().default("0"), acquisitionChannel: text("acquisition_channel"), createdAt: timestamp("created_at", { withTimezone: true }).notNull() });
export const orders = pgTable("orders", { id: text("id").primaryKey(), externalId: text("external_id"), customerId: text("customer_id"), total: numeric("total").notNull().default("0"), currency: text("currency").notNull().default("USD"), status: text("status").notNull(), orderedAt: timestamp("ordered_at", { withTimezone: true }).notNull() });
