"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, Bot, RefreshCw, Users, WalletCards, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { formatCurrency, formatNumber, formatRoas } from "@/lib/utils";

type Workspace = { campaigns: Array<{ id: string; name: string; source: string; status: string; spend: number; revenue: number; roas: number; conversions: number }>; creators: Array<{ id: string; handle: string; platform: string; display_name: string | null; followers: number; engagement_rate: number; enriched_at: string | null }>; jobs: Array<{ id: string; kind: string; status: string; records_synced: number; created_at: string }>; kpi: { spend: number; revenue: number; conversions: number; roas: number } };

export default function DashboardPage() {
  const [data, setData] = useState<Workspace | null>(null);
  const [error, setError] = useState("");
  const [syncing, setSyncing] = useState(false);
  const load = async () => { const response = await fetch("/api/workspace", { cache: "no-store" }); const result = await response.json(); if (!response.ok) setError(result.error); else setData(result); };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30000); return () => window.clearInterval(timer); }, []);
  const totals = useMemo(() => data?.campaigns.length ?? 0, [data]);
  const queueSync = async () => { setSyncing(true); await fetch("/api/workspace", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "sync", kind: "full" }) }); await load(); setSyncing(false); };
  if (error) return <Card><CardContent className="p-6"><p className="font-medium">Live workspace unavailable</p><p className="mt-1 text-sm text-muted-foreground">{error}</p><Button className="mt-4" onClick={() => void load()}>Retry</Button></CardContent></Card>;
  if (!data) return <div className="flex min-h-64 items-center justify-center text-sm text-muted-foreground">Loading live workspace…</div>;
  return <div className="flex flex-col gap-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">Command center</h1><Badge variant="secondary" className="gap-1"><Activity className="size-3" data-icon="inline-start" />Live</Badge></div><p className="mt-1 text-sm text-muted-foreground">Shared campaign intelligence, creator context, and sync health.</p></div><Button variant="outline" onClick={() => void queueSync()} disabled={syncing}><RefreshCw className={syncing ? "animate-spin" : ""} data-icon="inline-start" />{syncing ? "Queueing…" : "Sync now"}</Button></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={WalletCards} label="Revenue" value={formatCurrency(data.kpi.revenue)} /><Metric icon={Zap} label="Ad spend" value={formatCurrency(data.kpi.spend)} /><Metric icon={Activity} label="Blended ROAS" value={formatRoas(data.kpi.roas)} /><Metric icon={Users} label="Conversions" value={formatNumber(data.kpi.conversions)} /></div>
    <div className="grid gap-4 lg:grid-cols-[1.4fr_1fr]"><Card><CardHeader><CardTitle>Campaign performance <span className="text-sm font-normal text-muted-foreground">({totals} live campaigns)</span></CardTitle></CardHeader><CardContent><div className="flex flex-col gap-3">{data.campaigns.length ? data.campaigns.map(c => <div key={c.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><p className="font-medium">{c.name}</p><p className="text-xs capitalize text-muted-foreground">{c.source} · {c.status}</p></div><div className="flex gap-5 text-right text-sm"><div><p className="text-muted-foreground">Revenue</p><p className="font-medium">{formatCurrency(Number(c.revenue))}</p></div><div><p className="text-muted-foreground">ROAS</p><p className="font-medium">{formatRoas(Number(c.roas))}</p></div></div></div>) : <p className="py-8 text-center text-sm text-muted-foreground">No campaigns yet. Queue a sync or add one from Workflows.</p>}</div></CardContent></Card><Card><CardHeader><CardTitle>Creator context</CardTitle></CardHeader><CardContent><div className="flex flex-col gap-3">{data.creators.length ? data.creators.slice(0, 5).map(c => <div key={c.id} className="flex items-center justify-between gap-3"><div><p className="font-medium">@{c.handle}</p><p className="text-xs capitalize text-muted-foreground">{c.platform} · {c.display_name ?? "Enriched profile"}</p></div><div className="text-right text-sm"><p className="font-medium">{formatNumber(Number(c.followers))}</p><p className="text-xs text-muted-foreground">followers</p></div></div>) : <p className="py-8 text-center text-sm text-muted-foreground">Enrich a creator to attach real social stats to campaigns.</p>}</div></CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Bot className="size-4" />Sync activity</CardTitle></CardHeader><CardContent><div className="flex flex-col gap-2">{data.jobs.length ? data.jobs.map(j => <div key={j.id} className="flex items-center justify-between rounded-md border px-3 py-2 text-sm"><span>{j.kind} sync</span><span className="flex items-center gap-3"><span className="text-muted-foreground">{j.records_synced} records</span><Badge variant={j.status === "completed" ? "secondary" : "outline"}>{j.status}</Badge></span></div>) : <p className="text-sm text-muted-foreground">No sync jobs yet.</p>}</div></CardContent></Card>
  </div>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: string }) { return <Card><CardContent className="flex items-center gap-3 p-4"><div className="flex size-9 items-center justify-center rounded-md bg-primary/10 text-primary"><Icon className="size-4" /></div><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-lg font-semibold tabular-nums">{value}</p></div></CardContent></Card>; }
