"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowUpRight, Bot, CheckCircle2, RefreshCw, Users, WalletCards, Zap } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatCurrency, formatNumber, formatRoas } from "@/lib/utils";

type Workspace = { campaigns: Array<{ id: string; name: string; source: string; status: string; spend: number; revenue: number; roas: number; conversions: number }>; creators: Array<{ id: string; handle: string; platform: string; display_name: string | null; followers: number; engagement_rate: number; enriched_at: string | null }>; jobs: Array<{ id: string; kind: string; status: string; records_synced: number; created_at: string }>; kpi: { spend: number; revenue: number; conversions: number; roas: number } };

export default function DashboardPage() {
  const [data, setData] = useState<Workspace | null>(null);
  const [error, setError] = useState("");
  const [syncing, setSyncing] = useState(false);
  const load = async () => { try { const response = await fetch("/api/workspace", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load workspace"); setData(result); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load workspace"); } };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30000); return () => window.clearInterval(timer); }, []);
  const queueSync = async () => { setSyncing(true); try { await fetch("/api/workspace", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "sync", kind: "full" }) }); await load(); } finally { setSyncing(false); } };
  if (error) return <Card className="mx-auto max-w-xl"><CardContent className="flex flex-col items-center gap-3 p-8 text-center"><Activity className="size-8 text-destructive" /><p className="font-semibold">Live workspace unavailable</p><p className="text-sm leading-relaxed text-muted-foreground">{error}</p><Button onClick={() => void load()}>Retry connection</Button></CardContent></Card>;
  if (!data) return <div className="flex min-h-64 items-center justify-center"><div className="flex items-center gap-3 text-sm text-muted-foreground"><RefreshCw className="size-4 animate-spin" />Loading your live workspace…</div></div>;
  return <div className="flex flex-col gap-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2"><Badge variant="secondary" className="gap-1.5"><span className="size-1.5 rounded-full bg-primary" />Live data</Badge><span className="text-xs text-muted-foreground">Auto-refreshes every 30s</span></div><h1 className="text-3xl font-semibold tracking-tight text-balance">Good morning, here&apos;s the signal.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Your campaigns, creator context, and sync health in one calm command center.</p></div><Button onClick={() => void queueSync()} disabled={syncing}>{syncing ? <RefreshCw className="animate-spin" data-icon="inline-start" /> : <RefreshCw data-icon="inline-start" />}{syncing ? "Queueing sync…" : "Sync now"}</Button></header>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={WalletCards} label="Revenue" value={formatCurrency(data.kpi.revenue)} hint="Across synced campaigns" /><Metric icon={Zap} label="Ad spend" value={formatCurrency(data.kpi.spend)} hint="Paid media investment" /><Metric icon={Activity} label="Blended ROAS" value={formatRoas(data.kpi.roas)} hint="Revenue / spend" /><Metric icon={Users} label="Conversions" value={formatNumber(data.kpi.conversions)} hint="Tracked outcomes" /></div>
    <div className="grid gap-4 lg:grid-cols-[1.45fr_1fr]"><Card><CardHeader className="flex-row items-center justify-between space-y-0"><div><CardTitle>Campaign performance</CardTitle><p className="mt-1 text-xs text-muted-foreground">{data.campaigns.length} live campaigns</p></div><a href="/campaigns" className="inline-flex h-8 items-center gap-2 rounded-md px-3 text-xs font-medium text-primary transition-colors hover:bg-accent">View all <ArrowUpRight data-icon="inline-end" /></a></CardHeader><CardContent><div className="flex flex-col gap-2">{data.campaigns.length ? data.campaigns.map(c => <div key={c.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-background/60 p-4 transition-colors hover:bg-accent/50"><div><p className="font-medium">{c.name}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{c.source} · {c.status}</p></div><div className="flex gap-6 text-right text-sm"><div><p className="text-xs text-muted-foreground">Revenue</p><p className="mt-1 font-semibold tabular-nums">{formatCurrency(Number(c.revenue))}</p></div><div><p className="text-xs text-muted-foreground">ROAS</p><p className="mt-1 font-semibold tabular-nums text-primary">{formatRoas(Number(c.roas))}</p></div></div></div>) : <EmptyState text="No campaigns yet. Add one from Workflows or queue a sync." />}</div></CardContent></Card><Card><CardHeader><CardTitle>Creator context</CardTitle><p className="mt-1 text-xs text-muted-foreground">Social proof attached to your campaigns</p></CardHeader><CardContent><div className="flex flex-col gap-2">{data.creators.length ? data.creators.slice(0, 5).map(c => <div key={c.id} className="flex items-center justify-between gap-3 rounded-xl p-2 transition-colors hover:bg-accent/50"><div><p className="font-medium">@{c.handle}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{c.platform} · {c.display_name ?? "Enriched profile"}</p></div><div className="text-right"><p className="font-semibold tabular-nums">{formatNumber(Number(c.followers))}</p><p className="text-xs text-muted-foreground">followers</p></div></div>) : <EmptyState text="Enrich a creator to attach real social stats." />}</div></CardContent></Card></div>
    <Card><CardHeader className="flex-row items-center gap-2 space-y-0"><Bot className="size-4 text-primary" /><div><CardTitle>Sync activity</CardTitle><p className="mt-1 text-xs text-muted-foreground">Recent data movement across connected sources</p></div></CardHeader><CardContent><div className="flex flex-col gap-2">{data.jobs.length ? data.jobs.map(j => <div key={j.id} className="flex items-center justify-between rounded-xl border bg-background/50 px-4 py-3 text-sm"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-primary" />{j.kind} sync</span><span className="flex items-center gap-3"><span className="text-xs text-muted-foreground">{j.records_synced} records</span><Badge variant={j.status === "completed" ? "secondary" : "outline"}>{j.status}</Badge></span></div>) : <EmptyState text="No sync jobs yet." />}</div></CardContent></Card>
  </div>;
}
function EmptyState({ text }: { text: string }) { return <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</div>; }
function Metric({ icon: Icon, label, value, hint }: { icon: typeof Activity; label: string; value: string; hint: string }) { return <Card className="overflow-hidden"><CardContent className="flex items-start gap-3 p-5"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-4" /></div><div className="min-w-0"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold tracking-tight tabular-nums">{value}</p><p className="mt-1 truncate text-[11px] text-muted-foreground">{hint}</p></div></CardContent></Card>; }
